version: 1.0.{build}
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal

install:
  - ps: Start-FileDownload 'https://aka.ms/documentdb-emulator'
  - ps: msiexec.exe /i DocumentDB.Emulator.msi
  - ps: Start-Process 'C:\Program Files\Azure DocumentDB Emulator\DocumentDB.LocalEmulator.exe'

  